name: Spring Boot Service Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTRIBUTION }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build -x test
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: build/libs/*.jar

  deploy-server-1:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: Package

    - name: List downloaded files
      run: ls -la

    - name: Deploy JAR to Server 1
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_1_HOST }}
        username: ${{ secrets.SERVER_1_USERNAME }}
        key: ${{ secrets.SERVER_1_SSH_KEY }}
        source: "*.jar"
        target: "/home/pigplan"

    - name: Execute deployment script on Server 1
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_1_HOST }}
        username: ${{ secrets.SERVER_1_USERNAME }}
        key: ${{ secrets.SERVER_1_SSH_KEY }}
        script: |
          cd /home/pigplan
          pwd
          ls -la  # 현재 디렉토리 파일 확인
          
          # 기존 jar 백업
          if [ -f gitActionTest.jar ]; then
            cp gitActionTest.jar gitActionTest.jar.backup
          fi
          
          # 새로 전송된 JAR 파일 찾기
          NEW_JAR=$(find . -maxdepth 1 -name "*.jar" ! -name "*.backup" -type f -printf "%T@ %p\n" | sort -n | tail -1 | cut -f2- -d" ")
          
          if [ -n "$NEW_JAR" ]; then
            echo "Found new JAR file: $NEW_JAR"
            cp "$NEW_JAR" gitActionTest.jar
            chmod +x gitActionTest.jar
            echo "JAR file deployed successfully"
            ls -la gitActionTest.jar
            
            # 서비스 재시작
            if sudo systemctl is-active --quiet gitActionTest.service; then
              sudo systemctl restart gitActionTest.service
            else
              sudo systemctl start gitActionTest.service
            fi
            
            # 서비스 상태 및 로그 확인
            echo "Service status:"
            sudo systemctl status gitActionTest.service
            echo "Recent logs:"
            sudo journalctl -u gitActionTest.service -n 50 --no-pager
          else
            echo "No new JAR file found"
            exit 1
          fi

  deploy-server-2:
    needs: deploy-server-1
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: Package

    - name: List downloaded files
      run: ls -la

    - name: Deploy JAR to Server 2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_2_HOST }}
        username: ${{ secrets.SERVER_2_USERNAME }}
        key: ${{ secrets.SERVER_2_SSH_KEY }}
        source: "*.jar"
        target: "/home/pigplan"

    - name: Execute deployment script on Server 2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_2_HOST }}
        username: ${{ secrets.SERVER_2_USERNAME }}
        key: ${{ secrets.SERVER_2_SSH_KEY }}
        script: |
          cd /home/pigplan
          pwd
          ls -la  # 현재 디렉토리 파일 확인
          
          # 기존 jar 백업
          if [ -f gitActionTest.jar ]; then
            cp gitActionTest.jar gitActionTest.jar.backup
          fi
          
          # 새로 전송된 JAR 파일 찾기
          NEW_JAR=$(find . -maxdepth 1 -name "*.jar" ! -name "*.backup" -type f -printf "%T@ %p\n" | sort -n | tail -1 | cut -f2- -d" ")
          
          if [ -n "$NEW_JAR" ]; then
            echo "Found new JAR file: $NEW_JAR"
            cp "$NEW_JAR" gitActionTest.jar
            chmod +x gitActionTest.jar
            echo "JAR file deployed successfully"
            ls -la gitActionTest.jar
            
            # 서비스 재시작
            if sudo systemctl is-active --quiet gitActionTest.service; then
              sudo systemctl restart gitActionTest.service
            else
              sudo systemctl start gitActionTest.service
            fi
            
            # 서비스 상태 및 로그 확인
            echo "Service status:"
            sudo systemctl status gitActionTest.service
            echo "Recent logs:"
            sudo journalctl -u gitActionTest.service -n 50 --no-pager
          else
            echo "No new JAR file found"
            exit 1
          fi